# Generated by Django 4.0.3 on 2022-06-09 08:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.AddField(
            model_name='project',
            name='create',
            field=models.DateTimeField(default=datetime.date(2022, 6, 9)),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
