# Generated by Django 4.0.3 on 2022-06-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_created_project_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create',
        ),
    ]
