# Generated by Django 4.0.3 on 2022-06-10 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
