# Generated by Django 4.0.3 on 2022-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
